### ISSUE TITLE
I'm receiving a "NoMemoryError" when attempting to get words from a site.

### ISSUE THREAD

**Issue by metalkey** [digininja/CeWL#3] opened 2016-05-29 11:37 UTC
OS:
Kali 2.0 Rolling Release

Command executed:
cewl -v http://website.com

Error:
/usr/bin/cewl:813:in `block (2 levels) in <main>': failed to allocate memory (NoMemoryError)
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:280:in `block in do_callbacks'
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:279:in `each'
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:279:in `do_callbacks'
	from /usr/bin/cewl:179:in `block (3 levels) in start!'
	from /usr/bin/cewl:256:in `get_page'
	from /usr/bin/cewl:178:in `block (2 levels) in start!'
	from /usr/bin/cewl:176:in `each'
	from /usr/bin/cewl:176:in `block in start!'
	from /usr/bin/cewl:167:in `each'
	from /usr/bin/cewl:167:in `start!'
	from /usr/bin/cewl:138:in `start_at'
	from /usr/bin/cewl:694:in `<main>'

**Comment by digininja** [comment] 2016-05-29 11:50
What version of ruby are you using and how large is the site you are
spidering? Everything is held in memory so a very large site may fill the
memory.

**Comment by metalkey** [comment] 2016-05-29 12:20
Ruby Version:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

The site is not too large. I've used cewl many times before on much larger sites without any issues.
Does this assist at all?
http://stackoverflow.com/questions/23520758/failed-to-allocate-memory-no-memoryerror-in-ruby

**Comment by digininja** [comment] 2016-05-29 12:22
I'll have a look at it.

Could you try the latest version from github, the chaos branch, see if that
helps.

**Comment by metalkey** [comment] 2016-05-29 12:48
Just git cloned and retried. No luck unfortuantely.

**Comment by digininja** [comment] 2016-05-29 12:58
Don't suppose you can share the URL you are spidering can you?

**Comment by metalkey** [comment] 2016-05-29 13:52
Any way of providing it privately?

**Comment by digininja** [comment] 2016-05-29 14:07
Sure my address is in the source I think or on my site.

**Comment by digininja** [comment] 2016-06-14 10:56
I've tried to reproduce this on the site you sent over and didn't get any errors.

```
 $ time ./cewl.rb http://www.xxx/ -w /tmp/cewl_xxx
CeWL 5.2 (Some Chaos) Robin Wood (robin@digi.ninja) (https://digi.ninja)


real    278m42.768s
user    219m43.664s
sys     0m5.780s

$ wc /tmp/cewl_xxx
 26999  26999 227411 /tmp/cewl_xxx

```
Not sure if the ruby version has anything to do with it, this is what I'm on, nothing special, just what was on the box at the time.
```
$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
```

Not sure what to suggest next.

**Comment by metalkey** [comment] 2016-06-15 01:05
Strange, here's my current ruby version
`[root:~]# ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`

**Comment by digininja** [comment] 2016-06-15 07:52
Installed as close to that version as I can easily get and running now

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Comment by digininja** [comment] 2016-06-15 14:59
Worked for me again, slightly different word count but I'd expect that on a dynamic site.

```
$ time ./cewl.rb http://www.xxx/ -w /tmp/cewl_xxx
CeWL 5.2 (Some Chaos) Robin Wood (robin@digi.ninja) (https://digi.ninja)


real    285m48.378s
user    214m45.480s
sys     0m6.528s

 $ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

$ wc /tmp/cewl_afl2
 27664  27664 234677 /tmp/cewl_xxx

```
only 8 minutes difference in running time which is nice consistency.

**Comment by metalkey** [comment] 2016-06-16 06:47
i'm still receiving the same error. Btw, i noticed your version is 5.2. My version is 5.1 even after git cloning it from this repo. Any ideas what could be causing that?

**Comment by digininja** [comment] 2016-06-16 07:12
You aren't cloning the chaos branch. I'm no good with git but I think you
do the clone then do

git checkout "<name of chaos branch>"

**Comment by metalkey** [comment] 2016-06-16 07:41
Just got 5.2 but no luck. Really weird.

CeWL 5.2 (Some Chaos) Robin Wood (robin@digi.ninja) (https://digi.ninja)

./cewl.rb:901:in `block (3 levels) in <main>': failed to allocate memory (NoMemoryError)
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:280:in `block in do_callbacks'
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:279:in `each'
	from /usr/lib/ruby/vendor_ruby/spider/spider_instance.rb:279:in `do_callbacks'
	from ./cewl.rb:184:in `block (3 levels) in start!'
	from ./cewl.rb:261:in `get_page'
	from ./cewl.rb:183:in `block (2 levels) in start!'
	from ./cewl.rb:181:in `each'
	from ./cewl.rb:181:in `block in start!'
	from ./cewl.rb:172:in `each'
	from ./cewl.rb:172:in `start!'
	from ./cewl.rb:143:in `start_at'
	from ./cewl.rb:713:in `block in <main>'
	from ./cewl.rb:698:in `catch'
	from ./cewl.rb:698:in `<main>'
./cewl.rb http://www.website/ -w   111.04s user 1.29s system 94% cpu 1:58.77 total

**Comment by metalkey** [comment] 2016-06-16 07:41
ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by digininja** [comment] 2016-06-16 07:49
How much memory has your machine got? I'm running on a VM with 2gb I think.
Try watching top when it runs to see what happens in case you actually run
out of memory.

All the words and URLs are held in memory so it will take up a lot of space.

That makes me wonder about adding redis or sqlite support, would slow
things down but reduce overhead.

**Comment by metalkey** [comment] 2016-06-16 07:55
Really strange. My VM has 6GB allocated. Just ran it with top open. It stays below 1.8% all the way through.

**Comment by digininja** [comment] 2016-07-22 21:01
Closing this as I can't reproduce it, feel free to reopen if you find a way to do it.

**Closed by digininja** 2016-07-22 21:01 UTC
