### ISSUE TITLE
-o fails nearly 100% of the time

### ISSUE THREAD

**Issue by ZeroChaos-** [digininja/CeWL#10] opened 2016-07-18 14:59 UTC
Every time -o is used, eventually it hits a server which doesn't exist and cewl dies, producing no wordlist after hours or days of running.  Here is the error from verbose mode:

Unable to connect to the site, run in verbose mode for more information

The following error may help:
getaddrinfo: Temporary failure in name resolution
/usr/lib64/ruby/2.1.0/net/http.rb:879:in `initialize'
/usr/lib64/ruby/2.1.0/net/http.rb:879:in`open'
/usr/lib64/ruby/2.1.0/net/http.rb:879:in `block in connect'
/usr/lib64/ruby/2.1.0/timeout.rb:75:in`timeout'
/usr/lib64/ruby/2.1.0/net/http.rb:878:in `connect'
/usr/lib64/ruby/2.1.0/net/http.rb:863:in`do_start'
/usr/lib64/ruby/2.1.0/net/http.rb:852:in `start'
/usr/lib64/ruby/2.1.0/net/http.rb:1375:in`request'
/usr/bin/cewl:243:in `get_page'
/usr/bin/cewl:179:in`block (2 levels) in start!'
/usr/bin/cewl:177:in `each'
/usr/bin/cewl:177:in`block in start!'
/usr/bin/cewl:168:in `each'
/usr/bin/cewl:168:in`start!'
/usr/bin/cewl:139:in `start_at'
/usr/bin/cewl:701:in`<main>'
Caller
/usr/bin/cewl:199:in `get_page'
/usr/bin/cewl:179:in`block (2 levels) in start!'
/usr/bin/cewl:177:in `each'
/usr/bin/cewl:177:in`block in start!'
/usr/bin/cewl:168:in `each'
/usr/bin/cewl:168:in`start!'
/usr/bin/cewl:139:in `start_at'
/usr/bin/cewl:701:in`<main>'

**Comment by digininja** [comment] 2016-07-18 15:06
Will look into it. Is it when DNS failure happens? That's what the error
looks like.

**Comment by ZeroChaos-** [comment] 2016-07-18 19:51
yes, it appears to be when dns resolution fails.  Bad link to non-existent server or unstable dns (both possible) can cause this.

**Comment by digininja** [comment] 2016-07-21 09:39
I can't reproduce this, the error is thrown but the scan continues. I've added a more specific error catches and and now printing the url that failed in the error so see if that helps work out what is going on.

**Comment by ZeroChaos-** [comment] 2016-08-02 20:14
even without -o this seems to be happening.  

My command line:

cewl --depth 2 -m 8 -v -w rogue_one.words https://en.wikipedia.org/wiki/LucasArts

Relevant error:

Visiting: https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=ScummVM&id=723672106 referred from https://en.wikipedia.org/wiki/ScummVM, got response code 200
Attribute text found:
 Wikimedia Foundation Powered by MediaWiki Wikipedia (en) Wikipedia Atom feed Tertiary source Wikipedia:Who writes Wikipedia Wikipedia:General disclaimer Wikipedia:Citing Wikipedia APA style The MLA Style Manual MHRA Style Guide The Chicago Manual of Style Council of Science Editors Bluebook American Medical Association BibTeX LaTeX ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&amp;rfr_id=info%3Asid%2Fen.wikipedia.org%3Aarticle&amp;rft.type=encyclopediaArticle&amp;rft.title=ScummVM&amp;rft.date=2016-06-04&amp;rft.source=Wikipedia%2C+The+Free+Encyclopedia&amp;rft.aucorp=Wikipedia+contributors&amp;rft.publisher=Wikimedia+Foundation&amp;rft.artnum=723672106&amp;rft.identifier=https%3A%2F%2Fen.wikipedia.org%2Fw%2Findex.php%3Ftitle%3DScummVM%26oldid%3D723672106&amp;rft.language=en&amp;rft.format=text&amp;rft.rights=CC-BY-SA+3.0  Discussion about edits from this IP address [n] A list of edits made from this IP address [y] You are encouraged to create an account and log in; however, it is not mandatory You're encouraged to log in; however, it's not mandatory. [o] This is a special page which you cannot edit Search Wikipedia [f] Search Wikipedia for this text Go to a page with this exact name if it exists Visit the main page Visit the main page [z] Guides to browsing Wikipedia Featured content – the best of Wikipedia Find background information on current events Load a random article [x] Support us Visit the Wikipedia store Guidance on how to use and edit Wikipedia Find out about Wikipedia About the project, what you can do, where to find things A list of recent changes in the wiki [r] How to contact Wikipedia Upload files [u] A list of all special pages [q] Printable version of this page [p] wmf:Privacy policy Wikipedia:About Wikipedia:General disclaimer

Unable to connect to the site, run in verbose mode for more information

The following error may help:
Network is unreachable - connect(2) for "en.wikipedia.org" port 443
/usr/lib64/ruby/2.1.0/net/http.rb:879:in `initialize'
/usr/lib64/ruby/2.1.0/net/http.rb:879:in `open'
/usr/lib64/ruby/2.1.0/net/http.rb:879:in `block in connect'
/usr/lib64/ruby/2.1.0/timeout.rb:75:in `timeout'
/usr/lib64/ruby/2.1.0/net/http.rb:878:in `connect'
/usr/lib64/ruby/2.1.0/net/http.rb:863:in `do_start'
/usr/lib64/ruby/2.1.0/net/http.rb:852:in `start'
/usr/lib64/ruby/2.1.0/net/http.rb:1375:in `request'
/usr/bin/cewl:243:in `get_page'
/usr/bin/cewl:179:in `block (2 levels) in start!'
/usr/bin/cewl:177:in `each'
/usr/bin/cewl:177:in `block in start!'
/usr/bin/cewl:168:in `each'
/usr/bin/cewl:168:in `start!'
/usr/bin/cewl:139:in `start_at'
/usr/bin/cewl:701:in `<main>'
Caller
/usr/bin/cewl:199:in `get_page'
/usr/bin/cewl:179:in `block (2 levels) in start!'
/usr/bin/cewl:177:in `each'
/usr/bin/cewl:177:in `block in start!'
/usr/bin/cewl:168:in `each'
/usr/bin/cewl:168:in `start!'
/usr/bin/cewl:139:in `start_at'
/usr/bin/cewl:701:in `<main>'

**Comment by digininja** [comment] 2016-08-02 20:42
I'll give that a run and see what happens. How long does it normally take
before it crashes?

**Comment by digininja** [comment] 2017-04-30 21:30
couldn't reproduce and I've rewritten some of the offsite rules checking now so closing.

**Closed by digininja** 2017-04-30 21:30 UTC
